query ListUserTasks($userId: String!) @auth(level: USER) {
  tasks(
    where: { userId: { eq: $userId } }
    orderBy: [{ createdAt: DESC }]
  ) {
    id
    title
    completed
    createdAt
    dueDate
    category
  }
}