type Task @table {
  id: UUID! @default(expr: "uuidV4()")
  title: String!
  completed: Boolean! @default(value: false)
  userId: String!
  createdAt: Timestamp! @default(expr: "request.time")
  
  # Nossas novas colunas:
  dueDate: Date
  category: String
}